# Generated by Django 4.1.4 on 2022-12-20 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_group_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
