# Generated by Django 4.1.4 on 2022-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to="bidout-auction-v1/avatars/"),
        ),
    ]
