# Generated by Django 4.1.4 on 2023-07-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Suscriber",
            new_name="Subscriber",
        ),
    ]
