# Generated by Django 4.1.4 on 2023-03-25 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300, null=True)),
                ("show", models.BooleanField(default=False)),
                ("text", models.TextField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="fb",
            field=models.CharField(max_length=300, null=True, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="ig",
            field=models.CharField(max_length=300, null=True, verbose_name="Instagram"),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="tw",
            field=models.CharField(max_length=300, null=True, verbose_name="Twitter"),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="wh",
            field=models.CharField(max_length=300, null=True, verbose_name="Whatsapp"),
        ),
        migrations.DeleteModel(
            name="Reviews",
        ),
    ]
