# Generated by Django 4.1.4 on 2023-03-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_review_alter_sitedetail_fb_alter_sitedetail_ig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedetail",
            name="address",
            field=models.CharField(default="234, Lagos, Nigeria", max_length=300),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="email",
            field=models.EmailField(default="kayprogrammer1@gmail.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="fb",
            field=models.CharField(
                default="https://facebook.com", max_length=300, verbose_name="Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="ig",
            field=models.CharField(
                default="https://instagram.com",
                max_length=300,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="name",
            field=models.CharField(default="Kay's Auction House", max_length=300),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="phone",
            field=models.CharField(default="+2348133831036", max_length=300),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="tw",
            field=models.CharField(
                default="https://twitter.com", max_length=300, verbose_name="Twitter"
            ),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="wh",
            field=models.CharField(
                default="https://wa.me/2348133831036",
                max_length=300,
                verbose_name="Whatsapp",
            ),
        ),
    ]
