# Generated by Django 4.1.4 on 2023-03-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_category_listing_slug_listing_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
